
export default function SignalerPage() {
      return (
          <main className="min-h-screen bg-slate-50">
                <header className="bg-blue-900 px-5 py-4 text-white">
                        <h1 className="text-2xl font-bold">UL Guardian</h1>
                                <p className="text-sm text-blue-200">Nouveau signalement</p>
                                      </header>

                                            <section className="mx-auto max-w-xl px-5 py-8">
                                                    <h2 className="mb-6 text-2xl font-bold text-slate-900">
                                                              Signaler un incident
                                                                      </h2>

                                                                              <form className="space-y-5">
                                                                                        <div>
                                                                                                    <label className="mb-2 block font-semibold text-slate-700">
                                                                                                                  Type d’incident
                                                                                                                              </label>
                                                                                                                                          <select className="w-full rounded-lg border p-3">
                                                                                                                                                        <option>Agression</option>
                                                                                                                                                                      <option>Vol</option>
                                                                                                                                                                                    <option>Accident</option>
                                                                                                                                                                                                  <option>Harcèlement</option>
                                                                                                                                                                                                                <option>Incendie</option>
                                                                                                                                                                                                                              <option>Autre</option>
                                                                                                                                                                                                                                          </select>
                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                              <div>
                                                                                                                                                                                                                                                                          <label className="mb-2 block font-semibold text-slate-700">
                                                                                                                                                                                                                                                                                        Description
                                                                                                                                                                                                                                                                                                    </label>
                                                                                                                                                                                                                                                                                                                <textarea
                                                                                                                                                                                                                                                                                                                              className="min-h-32 w-full rounded-lg border p-3"
                                                                                                                                                                                                                                                                                                                                            placeholder="Décrivez ce qui s’est passé..."
                                                                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                            <div>
                                                                                                                                                                                                                                                                                                                                                                                        <label className="mb-2 block font-semibold text-slate-700">
                                                                                                                                                                                                                                                                                                                                                                                                      Niveau d’urgence
                                                                                                                                                                                                                                                                                                                                                                                                                  </label>
                                                                                                                                                                                                                                                                                                                                                                                                                              <select className="w-full rounded-lg border p-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                            <option>Faible</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                          <option>Normale</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <option>Urgente</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <option>Critique</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </select>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <label className="flex items-center gap-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <input type="checkbox" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <span>Je souhaite rester anonyme</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </label>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              type="submit"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="w-full rounded-xl bg-red-600 px-6 py-4 font-bold text-white"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Envoyer le signalement
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
